### ISSUE TITLE
PNG with transparent background

### ISSUE THREAD

**Issue by gchudnov** [kapouer/node-webkitgtk#15]
Is there a way to save PNG with transparent background?

Previously, there was [webkit_web_view_set_transparent](http://webkitgtk.org/reference/webkitgtk/stable/webkitgtk-webkitwebview.html#webkit-web-view-set-transparent) function that allowed to make WebKitWebView with transparent background.

But I don't see anything like that now.

**Comment by gchudnov** [comment]
that would be nice.

Right now we use the previous version of webkit-gtk with the function `webkit_web_view_set_transparent` included.

The service is written in Perl, uses the old version of webkit-gtk and I'm not happy with it at all.

It is used to render makers, map layers, badges (almost everything with transparency):
e.g.
```
http://www.provereno.ru/render/maps/cluster-markers/2427.html
becomes:
http://www.provereno.ru/render/maps/cluster-markers/2427.png
```
notice the transparent background.

The same issue with map layers:
```
http://www.provereno.ru/render/maps/tiles/9/309/161.html
becomes
http://www.provereno.ru/render/maps/tiles/9/309/161.png
^^
notice, there are white lines -- regional borders, rendered as SVG on HTML first and printed to PNG
```

Moreover, there are badges, PDF reports and other stuff. Almost everything is with transparent background (except PDF reports)

**Comment by kapouer** [comment]
@gchudnov could you have a look at upstream's answer ? Does his reply covers your needs ? (it sure covers mines).

**Comment by gchudnov** [comment]
hm, right now I'm not sure..
Going to make a branch and try the suggested solutions. I'll write back soon..

**Comment by kapouer** [comment]
http://www.webkitgtk.org/2015/01/20/webkitgtk2.7.4-released.html
give me a couple of days before it is usable in this module :)

**Comment by gchudnov** [comment]
that would be great, thanks!

**Comment by gchudnov** [comment]
If there anything I can do to help with webkitgtk2.7.4 integration, let me know..

**Comment by kapouer** [comment]
I'm unfamiliar with conditional compilation - i need to learn how to write stuff like
#if webViewHasThatMethod
  ...
#endif

if you know that, you can help me !

**Comment by kapouer** [comment]
That's because i'd like to keep webkitgtk 2.6 compatibility until 2.8 is out.

**Comment by gchudnov** [comment]
yeah, I understand that.
I'm installing  webkitgtk2.7.4 in a container now and try to implement feature detection. I'll let you know as soon as I get anything.

**Comment by gchudnov** [comment]
Sorry, didn't have much time lately.
I issued a pull-request with the changes to support transparency

**Comment by kapouer** [comment]
Closed by https://github.com/kapouer/node-webkitgtk/releases/tag/1.13.0

**Comment by kapouer** [comment]
Such a fun tool to work with... see wiki :)
