### ISSUE TITLE
The library halts on an invalid URL

### ISSUE THREAD

**Issue by gchudnov** [kapouer/node-webkitgtk#24]
When using the `load` function and providing an URL like this: "www.github.com" (without http://)
```javascript
.load(href, loadParams, cb);
```

the library halts with the following error
```
** (node:4571): CRITICAL **: gchar* webkit_favicon_database_get_favicon_uri(WebKitFaviconDatabase*, const gchar*): assertion 'pageURL' failed
```

Not sure if there anything can be done?

**Comment by kapouer** [comment]
indeed,
i could check url have a known protocol, but webkit2gtk itself could also handle more gracefully this case.

**Comment by kapouer** [comment]
This is fixed by https://github.com/kapouer/node-webkitgtk/commit/ff464b2383ca02940829461d436175e88e8c74fc and release as 1.18.11
