### ISSUE TITLE
support iojs v3 and the upcoming node.js v4

### ISSUE THREAD

**Issue by gchudnov** [kapouer/node-webkitgtk#31]
It looks it is needed to update the NAN library and the code that uses it.

I made the initial [transformation](https://github.com/gchudnov/node-webkitgtk/commit/edb8a898a9d25ccf2c127fb6600838958ba7f78f).

The code compiles but there is at least one `double free or corruption` error.
I may have missed something, didn't have time to debug the problem yet. :(

**Comment by kapouer** [comment]
Thanks, i'm still on 0.10 but was planing to move to iojs soon.

**Comment by kapouer** [comment]
Just realized nan 2.0.5 is compatible with node 0.10.
I'm fixing double-free errors !

**Comment by kapouer** [comment]
@gchudnov could you test with master please ?

**Comment by kapouer** [comment]
@gchudnow let me also warn you that a *lot* of changes happened under the hood.
I'm interested by more bug reports :)

**Comment by gchudnov** [comment]
just tested,
it works, thank you!

when running tests, only 2 are failing on my machine:
```
  1) init method should initialize cacheDir with call to init:
     Uncaught Error: expected false to be truthy
      at test/init.js:16:24
      at FSReqWrap.cb [as oncomplete] (fs.js:212:19)

  2) load method should allow to load another uri just after:
     Uncaught TypeError: Cannot read property 'toString' of undefined
      at test/load.js:71:28
      at webkitgtk.js:336:3
      at WebKit.<anonymous> (webkitgtk.js:863:27)
```

(1) marked as `this test doesn't really work` so it might be ok.

Guess, this issue might be closed. The library works in io.js v3 now and _should_ work in the upcoming node.js v4, as the authors on NAN promised compatibility.

--
Today I'll test it more. I'll let you know if there is anything else.

**Comment by kapouer** [comment]
HTe first one is ok to fail.
```
  2) load method should allow to load another uri just after:
     Uncaught TypeError: Cannot read property 'toString' of undefined
      at test/load.js:71:28
      at webkitgtk.js:336:3
      at WebKit.<anonymous> (webkitgtk.js:863:27)
```
But that one shouldn't fail - or if it does, not like that. It's probably something buggy hidden behind it.

**Comment by kapouer** [comment]
Hey it's done !

**Comment by gchudnov** [comment]
That's great, thank you!
I'll run it today on node.js v4 :)
