### ISSUE TITLE
No property named "allow-file-access-from-file-urls"

### ISSUE THREAD

**Issue by skerit** [kapouer/node-webkitgtk#37]
When trying to enable local file access you get this error:

    (node:25711): GLib-GObject-WARNING **: g_object_set_valist: object class 'WebKitSettings' has no property named 'allow-file-access-from-file-urls'

I was browsing the [webkitgtk documentation](http://webkitgtk.org/reference/webkitgtk/stable/WebKitWebSettings.html#WebKitWebSettings--enable-file-access-from-file-uris), and that seems to state the option is now "enable-file-access-from-file-uris"

**Comment by kapouer** [comment]
Which version of webkigtk are you building node-webkitgtk against ?

**Comment by kapouer** [comment]
Granted it's probably a bold typo... fixing it !

**Comment by kapouer** [comment]
Ugh, not a typo, just a mistake.

**Comment by skerit** [comment]
I installed `libwebkit2gtk-4.0-dev` on my Ubuntu 15.10 install, from the main repos.

I just edited it manually in the source and rebuilt it, but now I'm getting

    (node:27247): GLib-GObject-WARNING **: g_object_set_valist:
    object class 'WebKitSettings' has no property named 'enable-file-access-from-file-uris'

So even though it should be using the correct option according to the documentation, it's still not working over here :/

**Comment by kapouer** [comment]
ha damn
i was right, doc was wrong, and i ran too quickly on this.

**Comment by kapouer** [comment]
ok the problem is that you're reading webkitgtk docs, while here we have webkit2gtk bindings:
http://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#WebKitSettings--allow-file-access-from-file-urls

**Comment by skerit** [comment]
Ah, that's good to know.

But even so, the original option also does not work.
Any idea as to why?

**Comment by kapouer** [comment]
Because it's available since version 2.10 and you have 2.8.x.

**Comment by skerit** [comment]
Ah yes, at the bottom of the README.md it said version 2.8.x so I just went with that. By using the Webkit team unstable ppa, that part of the problem has now resolved.

I'm still getting "Not allowed to load local resource" inside the webkit window itself, but I'm guessing that's a bug on webkit2gtk's part.

**Comment by kapouer** [comment]
Also as you can see i just pushed something nicer for the next user.

**Comment by skerit** [comment]
Great, thanks :)

**Comment by kapouer** [comment]
"allow-file-access-from-file-urls" actually allows one to load file:// urls only if current location is also a file:// url.

**Comment by kapouer** [comment]
Not publishing to npm until you're done finding problems :)

**Comment by skerit** [comment]
Well I think they've all been resolved :)
Creating an empty file and loading that works fine, allowing me to experiment with local files.

I've got a few extra requests regarding the "enable-mediasource" and "enable-media-stream" options, because the [MediaSource](https://developer.mozilla.org/nl/docs/Web/API/MediaSource) api seems to be disabled by default. Shall I create a new issue for that?

**Comment by kapouer** [comment]
Yes, please do.
