### ISSUE TITLE
MediaSource and MediaStream flags

### ISSUE THREAD

**Issue by skerit** [kapouer/node-webkitgtk#38]
The [MediaSource](https://developer.mozilla.org/nl/docs/Web/API/MediaSource) API allows the browser to use streams coming from JavaScript to play audio & video.

The MediaStream API allows recording video and audio.

They're currently disabled by default in webkit2gtk, but can be enabled with [these options](http://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#WebKitSettings--enable-mediasource):

* enable-mediasource
* enable-media-stream

Thanks!

**Comment by kapouer** [comment]
I'm doing something to fix how settings were arbitrarily chosen to be settable or not. That takes longer than simply adding those two options.

**Comment by kapouer** [comment]
In version 3.4.0 you can pass any parameter from
http://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html
in the load() options.
