### ISSUE TITLE
$TMPDIR/.Xn-lock is not removed when webkitgtk spawns xvfb and is killed

### ISSUE THREAD

**Issue by kapouer** [kapouer/node-webkitgtk#39]
Can it be avoided ?

**Comment by gchudnov** [comment]
Guess the solution might be remove these files on startup after checking these locks?

**Comment by kapouer** [comment]
Well, nothing guarantees they belong to us... i wonder if #33 fixes the issue altogether.

**Comment by kapouer** [comment]
It doesnt :(

**Comment by kapouer** [comment]
While #33 does not fix the issue, it makes it much less worse, because it will only spawn one xvfb instance during the application lifetime.

**Comment by kapouer** [comment]
xvfb-run now does that job on our behalf...
