### ISSUE TITLE
Using Linux FB 

### ISSUE THREAD

**Issue by Coretool** [kapouer/node-webkitgtk#40]
Hi, is there a way to use the Linux FB with this module ? Do I have to switch out your GTK version with GTK-fb or is there an other thing to do?

**Comment by kapouer** [comment]
I can't say, but i'm looking at it. Please add more info if have some, as i don't have much knowledge about gtk running on directfb.

**Comment by kapouer** [comment]
All i can find about GtkFb or directfb is old and dead upstream stuff.
The next best thing will be wayland, in the meanwhile you need xvfb - which is quite easy to setup on a linux distribution.
Closing.
