### ISSUE TITLE
Empty window with transparent background and hanging process under weston

### ISSUE THREAD

**Issue by regular** [kapouer/node-webkitgtk#58]
When I run `webkitgtk --show http://www.google.com` all I get is a transparent window (titlebar and border are visible, the rest shows the desktop background or whatever is behind the window)

Also, I get no prompt and the REPL hangs until i hit Ctrl-C, or maybe that's intended behaviour?

I am under Arch with webkit2gtk-2.14.2-2 installed.

Do you have any idea what could be going on?

Thanks!

**Comment by regular** [comment]
WHen I run `npm test`,  all tests pass.

**Comment by kapouer** [comment]
No, you should get the window with the expected page and the prompt.
Let's cover the basics:
- do you run under x11 or wayland ?
- do you see any kind of warning ?

**Comment by regular** [comment]
I run weston on wayland (vert barebones)
If I run 
```
GDK_BACKEND=x11 webkitgtk --show http://www.google.com
```
it behaves like you describe: I see the page and get a prompt.
However, without `GDK_BACKEND=x11`, the web content becomes invisible while the window decorations are still being rendered.

**Comment by regular** [comment]
And no, there's no warning

**Comment by kapouer** [comment]
I noticed that bug under wayland too. I'll fix it soon-ish.

**Comment by regular** [comment]
So, you know what is causing it? Or have an idea? I'd be interested in knowing. I'm currently building webkit2gtk from sources to be able to play with it's build options. [This](https://bugs.webkit.org/show_bug.cgi?id=115803) gave me the idea of maybe having to enable the EGL backend

**Comment by kapouer** [comment]
Not sure about that. It should work with wayland, period. Epiphany does.

**Comment by regular** [comment]
Solved it. Replaced official arch package with [webkit2gtk-unstable](https://aur.archlinux.org/packages/webkit2gtk-unstable/). Works out of the box.

**Comment by kapouer** [comment]
Oh! Good to know.
