### ISSUE TITLE
Do you have problems running tests in Travis CI?

### ISSUE THREAD

**Issue by zcbenz** [kapouer/node-webkitgtk#70]
Hi there, I'm also developing a project using webkit2gtk, and I encountered some strange problems running tests on Travis CI. For example, when loading `about:blank`, the `WEBKIT_LOAD_STARTED` event is emitted but I can never get the `WEBKIT_LOAD_FINISHED` event.

I see you are also running tests on Travis CI, and after checking the output of your tests, it seems that you also have similar problems? I just want to check whether I'm the only one that has these problems.

**Comment by kapouer** [comment]
Indeed, i never took the time to finish setting up tests on travis.

**Comment by kapouer** [comment]
As far as i remember, it will require setting up a Docker image.

**Comment by zcbenz** [comment]
Thanks for feedback, I just went to use Circle CI, which works perfectly when running webkit2gtk tests.
