### ISSUE TITLE
Set window position on screen ?

### ISSUE THREAD

**Issue by muhammadsayuti** [kapouer/node-webkitgtk#72]
Is there any way to set window position on screen ? i need to make my window always show at the bottom of the screen.

**Comment by kapouer** [comment]
Not at the moment.
However there are DOM-level `window` methods:
- moveTo / moveBy
- resizeTo / resizeBy

They are not doing anything right now, but if enabling them is easy, i'd add that option to this module.

**Comment by kapouer** [comment]
I think i found the code in epiphany to make it work ! Trying...

**Comment by kapouer** [comment]
I added support in version 4.8.0. If you could test it before i publish, it would be awesome.
Here only "resizeTo" works but not perfectly. I suspect gnome-shell or wayland ignores `gtk_window_move` calls.

**Comment by muhammadsayuti** [comment]
which branch ? i'll try to boot to my other OS that using X

**Comment by kapouer** [comment]
You can use master branch, `npm install kapouer/node-webkitgtk` should do it.

**Comment by muhammadsayuti** [comment]
it work, now my problem is how to expose an api to this webview, so that the running javascript can access it, is it using webkit2gtk-web-extension ?

**Comment by kapouer** [comment]
If you want to place the window from the node module, you can execute a js function inside the web page using
```
var dims = {
  height: 400
};
webview.run(function(dims, done) {
  window.moveTo(0, window.screen.height - dims.height);
  window.resizeTo(window.screen.width, dims.height);
}, dims, function(err) {

});
```

**Comment by kapouer** [comment]
You can also pass parameters to caller (like in this example) and the callee can return parameters, see README.md.

**Comment by muhammadsayuti** [comment]
okay thanks, btw how i can get the window id ?
i'm trying to use this library with [node-x11](https://github.com/sidorares/node-x11) but i don't know how to get the window id, any clue ?

**Comment by kapouer** [comment]
I'm not sure i understand what's a window id. Could you find the relevant gtk doc ?

**Comment by muhammadsayuti** [comment]
some reference i've found:
- [http://soc.if.usp.br/manual/libgtk2.0-doc/faq/x530.html](http://soc.if.usp.br/manual/libgtk2.0-doc/faq/x530.html)
- [https://stackoverflow.com/questions/1879326/how-can-i-retrieve-window-id-of-gtk-window](https://stackoverflow.com/questions/1879326/how-can-i-retrieve-window-id-of-gtk-window)
- [https://developer.gnome.org/gtk3/stable/GtkWindow.html#GtkWindow--startup-id](https://developer.gnome.org/gtk3/stable/GtkWindow.html#GtkWindow--startup-id)
The first one is in Gtk 2, i don't know if it works or not, the last one is from GNOME doc only startup-id that i found with the name id but i don't know if that is what i'm looking for.

**Comment by kapouer** [comment]
FYI i've released (node-webkitgtk version 4.8.1 with resizeTo/moveTo support.

**Comment by muhammadsayuti** [comment]
@kapouer thx man but i have made my own based on your code, cuz i need xid from gdk-x11.
and i think there is some issue with the window where i can't have window size lower than 200,
so i made some adjustment using input region.
If you are interested i can do a pull request, you can check my code [here](https://github.com/muhammadsayuti/node-webkitgtk).
you can read the ISSUES file to know some common issues that i found.

**Comment by kapouer** [comment]
Interesting. I suppose several of these issues are libwebkitgtk-related.
Did you try the (updated) example [here](https://github.com/kapouer/node-webkitgtk/blob/master/examples/gtk.js) ?
